name: "gbraad's Dotfiles wmux app Action"
description: 'Wrapper for wmux related app command execution on GitHub runners'
author: "Gerard Braad <me@gbraad.nl>"
inputs:
  as_user:
    description: 'User to run the commands as (optional)'
    required: false
    default: ""
runs:
  using: 'composite'
  steps:
    - name: Execute wmux app command
      uses: gbraad-actions/zsh-action@main
      with:
        as_user: ${{ inputs.as_user }}
        run: |
          # Check if app function exists
          if ! type app >/dev/null 2>&1; then
            echo "Error: app function is not defined. Please make sure to run install first"
            exit 1
          fi
          
          # Execute wmux app command
          app wmux install
          app wmux service install
          app wmux service start